### ISSUE TITLE
publishing pre-compiled package

### ISSUE THREAD

**Issue by alexNvmind** [sindresorhus/is-svg#15]
Good day!
Currently I can not  build my frontend app because create-react-app fails to minify  `./node_modules/is-svg/index.js:7 `.
For what it's worth, I'm gona copy and paste this code straight to my `/src` and resolve issue in that way, but I thought you ought to know.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.

**Comment by SamVerschueren** [comment]
FYI the new `create-react-app` (beta probably) should resolve this.
