### ISSUE TITLE
Support detection of a stream?

### ISSUE THREAD

**Issue by dominic-p** [sindresorhus/is-svg#22]
I realize that you would need to have the entire SVG string to know if it is a valid SVG file, but as the readme says, this is meant to be more of a quick and dirty check than a full validation.

The API could be similar to the `file-type.stream()` function although it would be hard to know how many bytes of the stream to consume before testing.

Thoughts?

**Comment by sindresorhus** [comment]
I don't think that's a good idea. The check is already pretty loose even when checking the whole file. I don't think a stream interface makes sense here.

**Comment by dominic-p** [comment]
Fair enough. Thanks for the consideration.
