### ISSUE TITLE
"export 'default' (imported as 'isSvg') was not found in 'is-svg'

### ISSUE THREAD

**Issue by creage** [sindresorhus/is-svg#25]
```js
import isSvg from 'is-svg';

isSvg('<svg/>');
```

but this works

```js
const isSvg = require('is-svg');
```

**Comment by papb** [comment]
This package does not support ESM (yet). If you're using TypeScript, you should use the following instead:

```ts
import isSvg = require('is-svg');
```

**Comment by creage** [comment]
Well, v4.2.1 works fine with ESM imports.

**Comment by devSajan** [comment]
I am facing the same issue, neither require nor import is working
