### ISSUE TITLE
Update ava build dependency to latest version

### ISSUE THREAD

**Issue by pravi** [sindresorhus/is-svg#34]
Please update the dependency on ava to 4.x

**Comment by sindresorhus** [comment]
I don't really see the point of this issue. Dev dependencies have no impact on end-users.

**Comment by pravi** [comment]
I expected such an answer, but thought worth asking explicitly. It allows us to test all modules in Debian with latest version of Ava (we would like to maintain only a single version of tools and modules as much as possible). Would a pull request be accepted?
