### ISSUE TITLE
Very long (inifinite?) response time

### ISSUE THREAD

**Issue by gmetais** [sindresorhus/is-svg#7]
Hi and thanks a lot for this useful module!

I have a case where using is-svg is **very very slow**, maybe infinite.

It's not an SVG file, it's a JS. [Here is a gist](https://gist.github.com/gmetais/089deeefd5af2d20c845872ab8f12d01). I truncated the JS file to keep only the specific part that causes the problem. (It's not a valid script anymore, but that's not the problem.)

The problem seems to be in the html comments removal:
```js
buf.toString().replace(htmlCommentRegex, '')
```

I suppose it's a problem with the regexp, as I've already had some problems with infinite regexp on V8 in the past. I tested against Node 4.1.2 and 6.3.0.

Maybe a temporary fix would be to start testing against a very minimalist regexp (such as `/<svg/`) before removing the comments.

**Comment by sindresorhus** [comment]
// @stevemao

**Comment by stevemao** [comment]
Don't know if you ping the right person... But I think @kevva probably knows more details :)

**Comment by sindresorhus** [comment]
@stevemao [It's your regex.](https://github.com/sindresorhus/is-svg/blob/3df048398e4bafecbdf5f44a6a658fab829ffd03/index.js#L2) "The problem seems to be in the html comments removal"

**Comment by kevva** [comment]
Fixed in https://github.com/stevemao/html-comment-regex/commit/54615a8da50b105e83838cf2d7a482189aa1b451.

**Comment by stevemao** [comment]
Sorry didn't know you depend on my regex :) thanks for the trust. Happy to support 😄

**Comment by gmetais** [comment]
What a strange coincidence, I'm lost in Ipoh, Malaysia, and I see a comment from you @sindresorhus on Foursquare. You're everywhere :)

(Thanks everyone for the bug fix!)

**Comment by sindresorhus** [comment]
Hah. Try the ice coffee at http://4sq.com/heW3VO It's very good.
